FROM docker.io/library/buildpack-deps:focal-curl

ENV DEBIAN_FRONTEND noninteractive
RUN \
  # https://github.com/nodesource/distributions#ubuntu-versions
  mkdir -p /etc/apt/keyrings && \
  curl -sL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" >> /etc/apt/sources.list.d/nodesource.list && \
  apt-get -qq update && \
  # binutils provides ar - required to build deb \
  apt-get -qq install --no-install-recommends -y nodejs binutils && \
  apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

WORKDIR /project

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

ENV DEBUG_COLORS true
ENV FORCE_COLOR true
